In [1]:
!pip install pygad

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.6/89.6 kB 2.6 MB/s eta 0:00:00


In [11]:
import pygad
import numpy as np

#дані по товарам (вага і ціна)
vaga = [12, 7, 11, 8, 9, 6, 7, 3, 1, 6, 2, 5, 4, 9]
cena = [24, 13, 23, 15, 16, 12, 13, 7, 4, 12, 5, 11, 9, 18]

max_vaga = 35

#фітнес ф-ція
def fitness_f(ga_instance, solution, solution_idx):
    suma_vagi = 0
    suma_cini = 0

    for i in range(len(solution)):
        if solution[i] == 1:
            suma_vagi += vaga[i]
            suma_cini += cena[i]

    if suma_vagi > max_vaga:
        return 0

    return suma_cini

#початкова популяція
start_pop = np.random.randint(2, size=(6, len(vaga)))
test_pop = np.random.randint(2, size=(4, len(vaga)))

#параметри алгоритму
gen = 30
batki = 3

select_type = 'sss'
cross_type = 'single_point'
mut_type = 'random'
mut_percent = 10

#створюємо генетичний алгоритм
ga = pygad.GA(gene_space=[0, 1], num_generations=gen, num_parents_mating=batki, fitness_func=fitness_f, sol_per_pop=6, num_genes=len(vaga), init_range_low=0, init_range_high=2, parent_selection_type=select_type, crossover_type=cross_type, mutation_type=mut_type, mutation_percent_genes=mut_percent)

#запуск
ga.run()

#результат
sol, fit, idx = ga.best_solution()
print('Рішення кросовера:\n', sol)

print('Цінність:\n', fit)
print('--------------------------')

#варіант з кросовером
ga2 = pygad.GA(gene_space=[0, 1], num_generations=30, num_parents_mating=3, fitness_func=fitness_f, sol_per_pop=6, num_genes=len(vaga), crossover_type='two_points', mutation_type='random', mutation_percent_genes=20)
ga2.run()
sol2, fit2, _ = ga2.best_solution()
print('Кросовер 2:\n', sol2)

print('Цінність 2:\n', fit2)
print('--------------------------')


#варіант номер три
ga3 = pygad.GA(gene_space=[0, 1], num_generations=30, num_parents_mating=4, fitness_func=fitness_f, sol_per_pop=8, num_genes=len(vaga), crossover_type='uniform', mutation_type='random', mutation_percent_genes=30)
ga3.run()
sol3, fit3, _ = ga3.best_solution()
print('Кросовер 3:\n', sol3)

print('Цінність 3:\n', fit3)
print('--------------------------')

Рішення кросовера:
 [1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0.]
Цінність:
 76
--------------------------
Кросовер 2:
 [0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0.]
Цінність 2:
 73
--------------------------
Кросовер 3:
 [0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1.]
Цінність 3:
 74
--------------------------
